diff

diff --git a/postgresql/ABUILD b/postgresql/ABUILD
--- a/postgresql/ABUILD
+++ b/postgresql/ABUILD
@@ -1,7 +1,7 @@
 # ABUILD generated by mkpkg_generator.sh
 
 pkgname=postgresql
-pkgver=9.3.1
+pkgver=9.3.4
 pkgbuild=1
 arch=("auto")
 
@@ -40,39 +40,34 @@ INSTALL_KEYS="DESTDIR=$pkgdir"
 
 
 after_build() {
-	go_src_dir
-	set -e
-	cd contrib
-		make -j${numjobs} || exit 1
-		make install DESTDIR=${pkgdir}
-	cd ..
+  go_src_dir
+  set -e
+  cd contrib
+    make -j${numjobs} || exit 1
+    make install DESTDIR=${pkgdir}
+  cd ..
 
-	# we don't want these, they are in the -libs package
-	for dir in src/interfaces src/bin/pg_config src/bin/psql src/bin/pg_dump; do
-	    make -C ${dir} DESTDIR="${pkgdir}" uninstall
-	done
-	rm "${pkgdir}/usr/man/man1/pg_config.1"
-	rm "${pkgdir}/usr/man/man1/pg_dump.1"
-	rm "${pkgdir}/usr/man/man1/pg_dumpall.1"
-	rm "${pkgdir}/usr/man/man1/pg_restore.1"
-	rm "${pkgdir}/usr/man/man1/psql.1"
+  # we don't want these, they are in the -libs package
+  for dir in src/interfaces src/bin/pg_config src/bin/psql src/bin/pg_dump; do
+     make -C ${dir} DESTDIR="${pkgdir}" uninstall
+  done
 
-	# clean up unneeded installed items
-	rm -rf "${pkgdir}/usr/include/postgresql/internal"
-	rm -rf "${pkgdir}/usr/include/libpq"
-	find "${pkgdir}/usr/include" -maxdepth 1 -type f -execdir rm {} +
+  # clean up unneeded installed items
+  rm -rf "${pkgdir}/usr/include/postgresql/internal"
+  rm -rf "${pkgdir}/usr/include/libpq"
+  find "${pkgdir}/usr/include" -maxdepth 1 -type f -execdir rm {} +
 
-	mkdir -p ${pkgdir}/var/log/pgsql
-	touch ${pkgdir}/var/log/pgsql/serverlog.new
-	install -D -m0644 $filedir/postgresql.logrotate ${pkgdir}/etc/logrotate.d/postgresql
+  mkdir -p ${pkgdir}/var/log/pgsql
+  touch ${pkgdir}/var/log/pgsql/serverlog.new
+  install -D -m0644 $filedir/postgresql.logrotate ${pkgdir}/etc/logrotate.d/postgresql
 
-	install -Dm0755 ${filedir}/postgresql.init ${pkgdir}/etc/init.d/postgresql
-	install -Dm0755 ${filedir}/postgresql.conf.d ${pkgdir}/etc/conf.d/postgresql
+  install -Dm0755 ${filedir}/postgresql.init ${pkgdir}/etc/init.d/postgresql
+  install -Dm0755 ${filedir}/postgresql.conf.d ${pkgdir}/etc/conf.d/postgresql
 
-	mkdir -p ${pkgdir}/var/lib/pgsql
-	chown -R pgsql:pgsql ${pkgdir}/var/log/pgsql
-	chown pgsql:pgsql ${pkgdir}/var/lib/pgsql
-	set +e
+  mkdir -p ${pkgdir}/var/lib/pgsql
+  chown -R pgsql:pgsql ${pkgdir}/var/log/pgsql
+  chown pgsql:pgsql ${pkgdir}/var/lib/pgsql
+  set +e
 }
 
 pgsql_libs() {
@@ -81,7 +76,7 @@ pgsql_libs() {
   tags="develop dev-db"
 }
 
-pgsql_prep() {
+pgsql_libs_prep() {
   go_src_dir
 
   # install license
diff --git a/postgresql/files/postgresql.init b/postgresql/files/postgresql.init
--- a/postgresql/files/postgresql.init
+++ b/postgresql/files/postgresql.init
@@ -1,54 +1,141 @@
 #!/sbin/runscript
-# Copyright 1999-2007 Gentoo Foundation
-# Modified for AgiliaLinux 2010-2012 by aix27249
+# Copyright 1999-2013 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
+# $Header: $
 
 extra_started_commands="reload"
 
-depend() {
-	need net
-	use logger
+get_config() {
+    [ -f ${PGDATA%/}/postgresql.conf ] || return 1
+
+    eval echo $(sed -e 's:#.*::' ${PGDATA%/}/postgresql.conf \
+        | awk '$1 == "'$1'" { print ($2 == "=" ? $3 : $2) }')
 }
 
+depend() {
+    use net
+    provide postgresql
+
+    if [ "$(get_config log_destination)" = "syslog" ]; then
+        use logger
+    fi
+}
+
+configured_port=$(get_config port)
+: ${configured_port:=${PGPORT}}
+socket_path=$(get_config unix_socket_directory)
+: ${socket_path:=/run/postgresql}
+
 checkconfig() {
-	if [ ! -d "$PGDATA" ] ; then
-		if [ ! -f $PGDATA/postgresql.conf ]; then
-			echo "PostgreSQL: bd creation..."
-			sudo -u $PGUSER /usr/bin/initdb -U $PGUSER -D $PGDATA 1> /dev/null
-		fi
-	fi
+    # Check that DATA_DIR has been set
+    if [ -z ${DATA_DIR} ] ; then
+        eerror "DATA_DIR not set"
+        eerror "HINT: Perhaps you need to update /etc/conf.d/postgresql"
+        return 1
+    fi
+
+    # Check that DATA_DIR exists
+    if [ ! -d ${DATA_DIR} ] ; then
+        eerror "Directory not found: ${DATA_DIR}"
+        eerror "HINT: Ensure that DATA_DIR points to the right path."
+        return 1
+    fi
+
+    if [ ! -f ${PGDATA}/postgresql.conf ]; then
+        echo "PostgreSQL: bd creation..."
+        sudo -u ${PGUSER} /usr/bin/initdb -U ${PGUSER} -D ${DATA_DIR} 1> /dev/null
+    fi
+
+
+    # Check for the existence of PostgreSQL's config files, and set the
+    # proper mode and ownership.
+    # Only three files should be checked as potentially other files
+    # may be in PGDATA that should not be touched.
+    local file
+    for file in postgresql pg_hba pg_ident ; do
+        file="${PGDATA%/}/${file}.conf"
+        if [ -f ${file} ] ; then
+            checkpath -f -m 0600 -o ${PGUSER}:${PGGROUP} ${file}
+        else
+            eerror "${file} not found"
+            eerror "HINT: mv ${DATA_DIR%/}/*.conf ${PGDATA}"
+            return 1
+        fi
+    done
+
+    # Set the proper permission for the socket path and create it if
+    # it doesn't exist.
+    checkpath -d -m 0775 -o ${PGUSER}:${PGGROUP} ${socket_path}
+    if [ -e ${socket_path%/}/.s.PGSQL.${configured_port} ] ; then
+        eerror "Socket conflict."
+        eerror "A server is already listening on:"
+        eerror "    ${socket_path%/}/.s.PGSQL.${configured_port}"
+        eerror "HINT: Change PGPORT to listen on a different socket."
+        return 1
+    fi
 }
 
 start() {
-	checkconfig || return 1
+    checkconfig || return 1
 
-	ebegin "Starting PostgreSQL"
+    ebegin "Starting PostgreSQL"
 
-	if [ -f "$PGDATA/postmaster.pid" ] ; then
-		rm -f "$PGDATA/postmaster.pid"
-	fi
+    rm -f ${DATA_DIR%/}/postmaster.pid
 
-	start-stop-daemon --start \
-		--pidfile "${PGDATA}/postmaster.pid" \
-		--user ${PGUSER} --group ${PGGROUP} \
-		--exec /usr/bin/postmaster \
-		-- \
-		-D "${PGDATA}" \
-		--silent-mode=true \
-		${PGOPTS}
+    local extraenv
+    local x
+    for x in ${PG_EXTRA_ENV} ; do
+        extraenv="${extraenv} --env ${x}"
+    done
 
-	eend $?
+    start-stop-daemon --start \
+        --user ${PGUSER} --group ${PGGROUP} \
+        --env "PGPORT=${configured_port}" \
+        ${extraenv} \
+        --pidfile ${DATA_DIR%/}/postmaster.pid \
+        --exec /usr/lib/pgsql/bin/pg_ctl \
+        -- start -s -w -t ${START_TIMEOUT} -l ${DATA_DIR%/}/postmaster.log \
+                 -D ${PGDATA} -o "--data-directory=${DATA_DIR} ${PGOPTS}"
+    local retval=$?
+
+    if [ $retval -ne 0 ] ; then
+        eerror "Check the log for a possible explanation of the above error. The log may be"
+        eerror "    ${DATA_DIR%/}/postmaster.log"
+        eerror "Or wherever you configured PostgreSQL @SLOT@ log messages to be sent."
+        eend $retval
+        return $retval
+    fi
+
+    eend $retval
 }
 
 stop() {
-	ebegin "Stopping PostgreSQL"
-	start-stop-daemon --stop --pidfile "${PGDATA}/postmaster.pid" \
-		--retry -TERM/${WAIT_FOR_DISCONNECT}/-INT/${WAIT_FOR_CLEANUP}/-QUIT
-	eend $?
+    local seconds=$(( ${NICE_TIMEOUT} + ${RUDE_TIMEOUT} + ${FORCE_TIMEOUT} ))
+    ebegin "Stopping PostgreSQL (this can take up to ${seconds} seconds)"
+
+    local retval
+    local retries=SIGTERM/${NICE_TIMEOUT}
+
+    if [ "${RUDE_QUIT}" != "NO" ] ; then
+        einfo "RUDE_QUIT enabled."
+        retries="${retries}/SIGINT/${RUDE_TIMEOUT}"
+    fi
+    if [ "${FORCE_QUIT}" = "YES" ] ; then
+        einfo "FORCE_QUIT enabled."
+        ewarn "A recover-run might be executed on next startup."
+        retries="${retries}/SIGQUIT/${FORCE_TIMEOUT}"
+    fi
+
+    # Loops through nice, rude, and force quit in one go.
+    start-stop-daemon --stop \
+        --exec /usr/lib/postgresql/bin/postgres \
+        --retry ${retries} \
+        --pidfile ${DATA_DIR%/}/postmaster.pid
+    eend
 }
 
 reload() {
-	ebegin "Reloading PostgreSQL configuration"
-	start-stop-daemon --stop --pidfile "${PGDATA}/postmaster.pid" --signal HUP
-	eend $?
+    ebegin "Reloading PostgreSQL configuration"
+    kill -HUP $(head -n1 ${DATA_DIR%/}/postmaster.pid)
+    eend $?
 }
