Update versions

diff --git a/python/ABUILD b/python/ABUILD
--- a/python/ABUILD
+++ b/python/ABUILD
@@ -1,5 +1,5 @@
 pkgname=python
-pkgver=2.7.6
+pkgver=2.7.9
 pkgbuild=1
 arch=("auto")
 _pybasever=${pkgver%.*}
@@ -13,60 +13,60 @@ source=("http://www.python.org/ftp/python/${pkgver}/Python-${pkgver}.tar.xz")
 build_deps="openssl readline sqlite bzip2 gdbm expat libffi"
 
 build() {
-	go_src_dir
-	burn_patches
+  go_src_dir
+  burn_patches
 
-	set -e
-	# Ensure that we are using the system copy of various libraries (expat, zlib and libffi),
-	# rather than copies shipped in the tarball
-	#rm -r Modules/expat
-	rm -r Modules/zlib
-	#rm -r Modules/_ctypes/{darwin,libffi}*
+  set -e
+  # Ensure that we are using the system copy of various libraries (expat, zlib and libffi),
+  # rather than copies shipped in the tarball
+  #rm -r Modules/expat
+  rm -r Modules/zlib
+  #rm -r Modules/_ctypes/{darwin,libffi}*
 
-	if [ "$ARCH" = "x86_64" ]; then
-		# Install to lib64 instead of lib:
-		zcat $filedir/python.x86_64.diff.gz |  patch -p1 --verbose || exit 1
-		# Python must report /usr/lib64/python2.7/site-packages as python_lib_dir:
-		zcat $filedir/python.pure64.diff.gz |  patch -p1 --verbose || exit 1
-	fi
+  if [ "$ARCH" = "x86_64" ]; then
+    # Install to lib64 instead of lib:
+    zcat $filedir/python.x86_64.diff.gz |  patch -p1 --verbose || exit 1
+    # Python must report /usr/lib64/python2.7/site-packages as python_lib_dir:
+    zcat $filedir/python.pure64.diff.gz |  patch -p1 --verbose || exit 1
+  fi
 
-	export OPT="${SLKCFLAGS}"
-	./configure --prefix=/usr --libdir=/usr/lib${LIBDIRSUFFIX} --enable-shared --with-threads --enable-ipv6 \
-		--enable-unicode=ucs4 --with-system-expat --with-system-ffi
+  export OPT="${SLKCFLAGS}"
+  ./configure --prefix=/usr --libdir=/usr/lib${LIBDIRSUFFIX} --enable-shared --with-threads --enable-ipv6 \
+    --enable-unicode=ucs4 --with-system-expat --with-system-ffi
 
-	make -j${numjobs}
-	set +e
+  make -j${numjobs}
+  set +e
 }
 
 after_build() {
-	go_src_dir
-	set -e
-	make DESTDIR=${pkgdir} altinstall
+  go_src_dir
+  set -e
+  make DESTDIR=${pkgdir} altinstall
 
-	ln -sf python${_pybasever} ${pkgdir}/usr/bin/python
-	ln -sf python${_pybasever}-config ${pkgdir}/usr/bin/python-config
+  ln -sf python${_pybasever} ${pkgdir}/usr/bin/python
+  ln -sf python${_pybasever}-config ${pkgdir}/usr/bin/python-config
 
-	ln -sf ../../libpython${_pybasever}.so \
-	${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/config/libpython${_pybasever}.so
+  ln -sf ../../libpython${_pybasever}.so \
+  ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/config/libpython${_pybasever}.so
 
-	mv ${pkgdir}/usr/bin/smtpd.py $pkgdir/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/
+  mv ${pkgdir}/usr/bin/smtpd.py $pkgdir/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/
 
-	# some useful "stuff"
-	install -dm755 ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/Tools/{i18n,scripts}
-	install -m755 Tools/i18n/{msgfmt,pygettext}.py \
-		${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/Tools/i18n/
-	install -m755 Tools/scripts/{README,*py} \
-		${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/Tools/scripts/
+  # some useful "stuff"
+  install -dm755 ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/Tools/{i18n,scripts}
+  install -m755 Tools/i18n/{msgfmt,pygettext}.py \
+    ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/Tools/i18n/
+  install -m755 Tools/scripts/{README,*py} \
+    ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/Tools/scripts/
 
-	# clean up #!s
-	find ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/ -name '*.py' | \
-		xargs sed -i "s|#[ ]*![ ]*/usr/bin/env python$|#!/usr/bin/env python|"
+  # clean up #!s
+  find ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/ -name '*.py' | \
+    xargs sed -i "s|#[ ]*![ ]*/usr/bin/env python$|#!/usr/bin/env python|"
 
-	# clean-up reference to build directory
-	sed -i "s#${srcdir}/Python-${pkgver}:##" \
-		${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/config/Makefile
+  # clean-up reference to build directory
+  sed -i "s#${srcdir}/Python-${pkgver}:##" \
+    ${pkgdir}/usr/lib${LIBDIRSUFFIX}/python${_pybasever}/config/Makefile
 
-	# license
-	install -Dm644 LICENSE ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
-	set +e
+  # license
+  install -Dm644 LICENSE ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
+  set +e
 }
